global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "user-service"
    static_configs:
      - targets: ["host.docker.internal:3001"]

  - job_name: "trip-service"
    static_configs:
      - targets: ["host.docker.internal:3003"]

  - job_name: "driver-service"
    static_configs:
      - targets: ["host.docker.internal:3002"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["host.docker.internal:3004"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["host.docker.internal:3005"]
